#!/bin/bash
if (( $(echo "$# < 1" | bc -l) )); then
  clear
  echo USAGE:    similarity_search     res.csv

exit
fi
com=,
fline=ligand

mol2path=$1

for k in *.smi
        do
        fline=$fline$com$k
done

echo $fline are the lead
echo $fline>$1

for i in *.mol2
        do
        res=$i
        for j in *.smi
                do
                tmp=`babel $j $i -ofpt|grep Tanimoto|awk -F '=' {'print $2'}`
                res=$res$com$tmp
                echo $res
        done
        echo $res>>$1
done
